name: Validate XML
on:
  pull_request:
  workflow_dispatch:
jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
      - run: sudo apt-get install libxml2-utils
      - run: bash ./scripts/validate-xml.sh
